# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: oel-mado <oel-mado@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/24 17:00:38 by oel-mado          #+#    #+#              #
#    Updated: 2024/10/31 00:40:56 by oel-mado         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = cc

FLAGS = -Wall -Wextra -Werror

NAME = libft.a

OBJ = 

SRC = ft_isalpha.c\
	ft_isdigit.c\
	ft_isprint.c\
	ft_isalnum.c\
	ft_isascii.c\
	ft_toupper.c\
	ft_tolower.c\
	ft_strlen.c\
	ft_strncpy.c\
	ft_strcat.c\
	ft_strncat.c\
	ft_strlcpy.c\
	ft_strlcat.c\
	ft_memset.c\
	ft_bzero.c\
	ft_memcpy.c\
	ft_memccpy.c\
	ft_memmove.c\
	ft_memchr.c\
	ft_memcmp.c\
	ft_substr.c\
	ft_strjoin.c\
	ft_strtrim.c\
	ft_split.c\
	ft_strmapi.c\
	ft_calloc.c\
	ft_strdup.c\
	ft_atoi.c\
	ft_itoa.c\
	ft_putchar_fd.c\
	ft_putendl_fd.c\
	ft_putnbr_fd.c\
	ft_putstr_fd.c

all:
clean:
	rm -fr ${OBJ}
fclean:
re:

